#!/bin/sh

export PATH=/bin:/sbin

mount -t proc none /proc
mount -t sysfs none /sys

# Some indication that init is working
echo 255 > /sys/class/leds/led:rgb_blue/brightness
sleep 3

mount -t tmpfs -o size=64k,mode=0755 tmpfs /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

sleep 3

# Enable USB networking
echo 0 > /sys/class/android_usb/android0/enable
echo rndis > /sys/class/android_usb/android0/functions
echo 1 > /sys/class/android_usb/android0/enable
echo 0 > /sys/class/leds/led:rgb_blue/brightness
sleep 3

# Configure USB Networking (IP address + DHCP server)
ifconfig rndis0 192.168.42.17
udhcpd

sleep 3

echo 255 > /sys/class/leds/led:rgb_red/brightness
telnetd -p 23 -l /bin/sh -F
